### PR TITLE
Add paused annotation

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
When debugging the deployment, it can be useful to pause the operator.

The reconciliation can be paused by adding annotation:
`"kubevirt.io/operator.paused": "true"`

```release-note
NONE
```

### CODE REVIEW

**Comment by omeryahud** [comment]
Is this ready for review? (still marked as draft)

**Comment by akrejcir** [comment]
Partially. I need to add test IDs.

**Comment by akrejcir** [comment]
This is ready for review, @vatsalparekh @omeryahud .

**Comment by akrejcir** [comment]
@omeryahud @vatsalparekh Can you take another look?

**Pull request merged**
