### PR TITLE
Add the missing RBAC permissions to clusterversions in the CSV

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

```release-note
None
```

### CODE REVIEW

**Comment by akrejcir** [comment]
Can you run `make container-build` to generate all needed files?
Our `Makefile` is confusing, but that command should generate all that is needed.

**Comment by nunnatsa** [comment]
> Can you run `make container-build` to generate all needed files? 

Done. Nothing in `git diff` after running `make container-build`

**Pull request merged**
