### PR TITLE
Add new column

### PR DESCRIPTION
**Pull request by opokornyy**
**What this PR does / why we need it**:

When 'oc get ssp' command is executed,
that the '.status.phase' field will be displayed.

**Which issue(s) this PR fixes**: 
Fixes # https://github.com/kubevirt/ssp-operator/issues/322

**Release note**:
```
Print column Phase when getting SSP objects by 'oc get ssp' command.
```
Signed-off-by: Ondrej Pokorny <opokorny@redhat.com>

### CODE REVIEW

**Comment by akrejcir** [comment]
@opokornyy One small thing: Can you run `go mod vendor` and `go mod tidy` ? It will update the copy of `api` package that is in the `vendor` directory.

**Comment by 0xFelix** [comment]
Looks good to me, but a release note would be helpful in my opinion.

**Comment by lyarwood** [comment]
I agree with @0xFelix , some brief releasenote text would be nice here if you have time @opokornyy, otherwise this looks ready.

**Comment by lyarwood** [comment]
Thanks :)

/approve

**Pull request merged**
