### PR TITLE
Release container and manifests on tag

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
When a commit is tagged TravisCI pushes the image to quay.io
and creates a github release.

```release-note
NONE
```

### CODE REVIEW

**Comment by akrejcir** [comment]
@omeryahud, are we going to change the image repository to something like: `quay.io/kubevirt/ssp-operator` ?

**Comment by omeryahud** [comment]
@akrejcir Yes, the repo already exists, you can update it in the makefile

**Pull request merged**
