### PR TITLE
Revert "feat: Add OWNERS_ALIASES and edit OWNERS file"

### PR DESCRIPTION
**Pull request by opokornyy**
**What this PR does / why we need it**:

Reverts https://github.com/kubevirt/ssp-operator/pull/625 because the functionality was different from what we have expected and there were no other options to test it before merging the PR.

**Release note**:
```
None
```

### CODE REVIEW

**Comment by jcanocan** [comment]
No 100% related, but as a follow-up, could you please sort alphabetically the aliases?

**Comment by opokornyy** [comment]
> Can you update the description and commit message with a reason for the revert?

Done

**Comment by opokornyy** [comment]
> No 100% related, but as a follow-up, could you please sort alphabetically the aliases?

Done

**Review by 0xFelix — APPROVED** [review]
/approve

**Pull request merged**
