### PR TITLE
fix: regenerate vendor files

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
Run "go mod tidy && go mod vendor" in the project root directory.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by ksimon1** [comment]
/lgtm
btw. how is possible, that this slip through the e2e tests?

**Comment by akrejcir** [comment]
Good question. I'm not sure.

**Review by codingben — APPROVED** [review]
/lgtm

This is really weird that it didn't catch this issue in the CI.

**Pull request merged**
