### PR TITLE
git rm -rf 

### PR DESCRIPTION
**Pull request by opokornyy**
**What this PR does / why we need it**:

This PR adds a notification to the README that the development has been moved from the master branch to the main branch.

**Release note**:
```
None
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
Can't we just drop the whole branch instead?

**Comment by opokornyy** [comment]
> Can't we just drop the whole branch instead?

@lyarwood what do you think about dropping the branch?

**Comment by lyarwood** [comment]
The only time I've done this in the past we kept `master` around to point people towards `main` but that might not be required here so I don't really mind either way. I'd like to hear input from @akrejcir (when you're back next week) , @ksimon1 and @codingben if possible before we decide either way.

**Comment by codingben** [comment]
I'd vote to rename `master` to `master-deprecated` and keep it, then after a few weeks remove it (or just keep it).

**Comment by ksimon1** [comment]
I agree to keep the branch for some time and then removes it

**Comment by opokornyy** [comment]
Can we merge this PR so there is a notification in the README, and then later rename/delete the master branch?

**Comment by lyarwood** [comment]
> Can we merge this PR so there is a notification in the README, and then later rename/delete the master branch?

/lgtm

Okay this works for me.

**Review by 0xFelix — APPROVED** [review]
/approve

ACK, when do we want to remove the master branch?

**Comment by opokornyy** [comment]
> /approve
> 
> ACK, when do we want to remove the master branch?

Lets wait for @akrejcir when he is back and then decide.

**Comment by akrejcir** [comment]
In `kubevirt` they removed the `master` branch. I think we can keep it temporarily, maybe until the next release, and then remove it.

**Pull request merged**
