### PR TITLE
[release-v0.17] Add VirtualMachineCRCErrors alert

### PR DESCRIPTION
**Pull request by machadovilaca**
**What this PR does / why we need it**:

This is a manual cherry-pick of #663

**Which issue(s) this PR fixes**: 

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Add VirtualMachineCRCErrors alert
```

/cc @lyarwood @akrejcir

### CODE REVIEW

**Comment by lyarwood** [comment]
@machadovilaca what's the justification for backporting this to v0.17?

**Comment by lyarwood** [comment]
> > @machadovilaca what's the justification for backporting this to v0.17?
> 
> @lyarwood since v0.18 is somewhat recent, many users are still in v0.17. This would be an important patch since CRC might cause a lot of issues in the clusters

@machadovilaca  v0.17 is already shipping downstream with v4.13, feature backports while potentially useful must have a much stronger justification to be accepted. I personally don't think this feature has it and as a result shouldn't be backported past the unshipped v0.18 branch.

@0xFelix @ksimon1 @akrejcir thoughts?

**Comment by akrejcir** [comment]
I agree. It would be useful if you had a Jira or Bugzilla ticket that was reviewed and agreed to go to 4.13.

**Comment by 0xFelix** [comment]
We're not going to backport this feature so I'm closing this.

**Pull request closed without merging**
