### PR TITLE
backport common templates v0.13.2

### PR DESCRIPTION
**Pull request by ksimon1**
**What this PR does / why we need it**:
backport common templates v0.13.2

**Release note**:
```
NONE
```
Signed-off-by: Karel Šimon <ksimon@redhat.com>

### CODE REVIEW

**Comment by omeryahud** [comment]
I am conflicted as to whether we should merge this templates file to master as well, WDYT?

**Comment by ksimon1** [comment]
We can merge it to master and to release-v0.1 as well

**Comment by ksimon1** [comment]
@omeryahud can you please check this PR?

**Pull request merged**
