### PR TITLE
Update common-instancetypes to v0.3.2

### PR DESCRIPTION
**Pull request by lyarwood**
common-instancetypes: Update bundle to v0.3.2

https://github.com/kubevirt/common-instancetypes/releases/tag/v0.3.2

**Release note**:
```release-note
Update common-instancetypes bundle to v0.3.2
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/approve

**Comment by lyarwood** [comment]
@akrejcir @0xFelix if either of you have time tomorrow I'm struggling to get to the bottom of this failure.

I can reproduce what I think is the same behaviour locally by deploying the sample SSP CR before running func tests. AFAICT this is breaking the clean up of the common instance type resources (and a few others).

I'm struggling to understand why these resources aren't owned by the func test SSP CR by the time this test runs and I can't see any obvious recent changes that might be causing this change in behaviour since `v0.3.1` landed.

**Comment by lyarwood** [comment]
@akrejcir @0xFelix okay so the rebase fixed the weird failures, if either of you can hit this agian.

**Review by 0xFelix — APPROVED** [review]
/lgtm

Thanks!

**Pull request merged**
