### PR TITLE
tests: RHEL: wait for DataVolume import and increase timeout

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
Waits specifically for DataVolume import, and increases timeout.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by dominikholler** [comment]
@akrejcir thanks for the quick PR!

**Comment by akrejcir** [comment]
Upgrade functests will fail until we release a new version.

/override ci/prow/e2e-upgrade-functests

**Pull request merged**
