### PR TITLE
reconcile: Restore test that go deleted by accident

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

Restore a test that got deleted by accident in
de115ba7e020d08719baecb963df78ade839f0b6.

**Which issue(s) this PR fixes**: 

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
/hold

Clarifying why de115ba was needed in the first place.

**Comment by akrejcir** [comment]
The PR https://github.com/kubevirt/ssp-operator/pull/728 fixed a bug: https://issues.redhat.com/browse/CNV-34614

Previously SSP assumed that if `.spec.source.PVC` field on `DataSource` is `nil`, then there is no `DataImportCron` that fills this field. The logic was correct when the `.spec.source.snapshot` filed did not exist. But after it was added, this logic is incorrect.

The PR fixed it, and now `DataSource` is reconciled by SSP only when there is no `DataImportCron`.

I've removed the unit test, because after the fix I thought it was not needed, and that the case of not reconciling `DataSource` by SSP is covered in a different test case.
Now I see that we are missing unit test for it.

@0xFelix, can you please change the test, so that it is not specific to snapshot? It should check that SSP does not overwrite changes to `DataSource` done by CDI.

**Comment by akalenyu** [comment]
> so that it is not specific to snapshot? It should check that SSP does not overwrite changes to `DataSource` done by CDI.

I would sleep better at night if we had a snapshot permutation to the test/keep this one

**Comment by akrejcir** [comment]
> I would sleep better at night if we had a snapshot permutation to the test/keep this one

Ok we can keep this test.

**Pull request merged**
