### PR TITLE
Log the reason why reconciliation is triggered

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
Logs the type and namespace/name of the object that triggered the reconciliation.

This change will be helpful for: https://bugzilla.redhat.com/2082912

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
I think it would be better to keep it as simple as possible and log all events in the `handler_hook`. The logs could be turned on/off with a debug switch. Transferring some of the events into the `Reconcile` function feels hacky and goes against the controller-runtime philosophy. It would be also more correct like this because in a series of events it is currently unclear which event is logged as reason for the reconciliation. I fear this could lead to false assumptions.

**Comment by akrejcir** [comment]
This PR probably introduces a bug. I'm looking into it.

/hold

**Comment by akrejcir** [comment]
Issue fixed.

/unhold

**Pull request merged**
