### PR TITLE
Update OWNERS file

### PR DESCRIPTION
**Pull request by akrejcir**
**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by akrejcir** [comment]
PR does not modify code.

/override ci/prow/e2e-functests
/override ci/prow/e2e-single-node-functests
/override ci/prow/e2e-upgrade-functests

**Comment by ksimon1** [comment]
@lyarwood can you please make sure you are added to github kubevirt group, so we can merge this PR?

**Comment by lyarwood** [comment]
> @lyarwood can you please make sure you are added to github kubevirt group, so we can merge this PR?

https://github.com/kubevirt/project-infra/pull/1975 FWIW

**Pull request merged**
