### PR TITLE
feat: multiarch compatibility to validator.Dockerfile

### PR DESCRIPTION
**Pull request by nestoracunablanco**
**What this PR does / why we need it**: s390x enablement

**Which issue(s) this PR fixes**: 

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note NONE

```

### CODE REVIEW

**Comment by codingben** [comment]
@nestoracunablanco Can you please change release note from empty to `None`?

**Comment by nestoracunablanco** [comment]
/test e2e-single-node-functests

@codingben: changed the release note to NONE. Thanks :)

**Review by 0xFelix — COMMENTED** [review]
/approve

**Pull request merged**
