### PR TITLE
Improve code: Use constants instead of string literals

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
Fixed code smells found by SonarCloud.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by kwiesmueller** [comment]
/retest
/lgtm
The security hotspot could be resolved afterwards as it seems to be this IP intentionally right?

**Comment by akrejcir** [comment]
> The security hotspot could be resolved afterwards as it seems to be this IP intentionally right?

Yes, that is why I changed the IP.

**Pull request merged**
