### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by windayski**
Signed-off-by: windayski <www19910911@163.com>

fix some typos

### CODE REVIEW

**Comment by akrejcir** [comment]
Hi, this PR needs to be rebased on the latest master. Otherwise the CI will not pass.
You don't need to create a new PR with the rebased code. It is enough to just push new changes to your fork of this repo.

**Comment by fabiand** [comment]
Please rebase

**Comment by akrejcir** [comment]
Hi @windayski, do you want to rebase this PR on the latest master?

**Comment by akrejcir** [comment]
The typo was fixed as part of PR #45.

/close

**Pull request closed without merging**
