### PR TITLE
[release-v0.18] Apply metrics name linter

### PR DESCRIPTION
**Pull request by akrejcir**
This is a cherry-pick of #621.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by akrejcir** [comment]
I forgot to backport this sooner.

/cc @assafad

**Review by 0xFelix — COMMENTED** [review]
/approve

Thanks!

**Comment by sradco** [comment]
@akrejcir Why was this not mereged?

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by 0xFelix** [comment]
Can you please rebase on `release-v0.18` to include 70ac067c8e948abf1a5d1c3655c794a27ba0ffc2 which fixes the failing functests?

**Pull request merged**
