### PR TITLE
[release-v0.16] Cleanup fixes for tests waiting for DVs to succeed 

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

This is a manual backport of #441 to release-v0.16.

Applying these patches was missed during the release of v0.16.

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by akrejcir** [comment]
I think we don't need to create a new release, since this PR only changes functional tests.
@0xFelix what do you think?

**Comment by 0xFelix** [comment]
@akrejcir Agreed, no immediate release required right now.

**Pull request merged**
