### PR TITLE
[release-v0.18] fix: Incorrect DataSource reconciliation

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
We hit this in previous versions, and think it may make sense to cherry pick, let us know what you think!

**Which issue(s) this PR fixes**: 

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
fix: Incorrect DataSource reconciliation
```

### CODE REVIEW

**Comment by akalenyu** [comment]
cc @0xFelix

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
