### PR TITLE
fix(CNV-28185): add required labels

### PR DESCRIPTION
**Pull request by codingben**
**What this PR does / why we need it**:

Add required labels:
- "app.kubernetes.io/managed-by"
- "app.kubernetes.io/version"
- "app.kubernetes.io/component"
- "app.kubernetes.io/part-of"

That are required by specific resources:
- ssp-operator (ServiceAccount)
- ssp-operator-metrics
- virt-template-validator

**Release note**:

```release-note
Add required labels to specific SSP resources.
```

### CODE REVIEW

**Comment by codingben** [comment]
It's draft because I'm trying to verify that the changes in this PR is enough.

**Comment by lyarwood** [comment]
@codingben would you mind recreating the PR against `main` now we've switched?

**Comment by codingben** [comment]
Replaced by https://github.com/kubevirt/ssp-operator/pull/608, that was created from `main` branch.

**Pull request closed without merging**
