### PR TITLE
Revert "api: Add config option for vm-console-proxy, deprecate feature gate"

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
The change should not be in the `v0.21` version, but in `v0.22`.

Reverts PR https://github.com/kubevirt/ssp-operator/pull/1018

**Release note**:
```release-note
Reverted API change from https://github.com/kubevirt/ssp-operator/pull/1018
```

### CODE REVIEW

**Comment by akrejcir** [comment]
The CI for this branch is not active yet: https://github.com/openshift/release/pull/55705
But it should be safe the revert.

**Review by 0xFelix — COMMENTED** [review]
/approve

**Review by codingben — APPROVED** [review]
/lgtm

**Pull request merged**
