### PR TITLE
Update common-templates bundle to version v0.27.1

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**: 

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Update common-templates bundle to v0.27.1
```

### CODE REVIEW

**Comment by akrejcir** [comment]
The failure is not related to this PR. It seems we have a broken Makefile for `v0.19`.

**Comment by akrejcir** [comment]
This PR should fix the workflow: https://github.com/kubevirt/ssp-operator/pull/1155

**Comment by akrejcir** [comment]
Can you rebase on the latest `release-v0.19`, that includes: https://github.com/kubevirt/ssp-operator/pull/1155 ?
It will fix the CI.

**Comment by fossedihelm** [comment]
Thank you @akrejcir! Really appreciate it, rebase done!

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
