### PR TITLE
fix: custom configuration of crio in testing cluster

### PR DESCRIPTION
**Pull request by ksimon1**
**What this PR does / why we need it**:
fix: custom configuration of crio in testing cluster

our e2e are not working due to permission issue in crio. cri-o/cri-o#7192 should revert the change.
Until that revert PR is released and available in ci envs, we have to set special configuration on crio on all nodes

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by lyarwood** [comment]
/approve

@ksimon1  would you mind posting a revert PR for this and/or an issue so we can track the removal of the workaround once https://github.com/cri-o/cri-o/pull/7192 makes it into our CI envs?

**Comment by lyarwood** [comment]
@ksimon1 @codingben any idea why this single pipeline is still failing?

**Comment by ksimon1** [comment]
all tekton lanes are failing. This is caused by the fact, that CDI can't import initial DV. I am investigating why it is happening (CDI team suspects some network issues)

**Comment by ksimon1** [comment]
This PR is no longer needed

**Pull request closed without merging**
