### PR TITLE
chore(observability): Bump operator observability version 0.0.24

### PR DESCRIPTION
**Pull request by jcanocan**
**What this PR does / why we need it**:

It updates the operator version and includes the required changes for avoiding the usage of deprecated functions.

**Which issue(s) this PR fixes**: 

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None.
```

### CODE REVIEW

**Comment by machadovilaca** [comment]
/lgtm

did you find it easy to understand the suggested implementation change to use operatorrules.Registry instance?
anything that could be improved in the docs?

**Comment by jcanocan** [comment]
> /lgtm
> 
> did you find it easy to understand the suggested implementation change to use operatorrules.Registry instance? anything that could be improved in the docs?

Hey! Thanks for your review.
I've found particularly useful this change: https://github.com/machadovilaca/operator-observability/pull/14/files#diff-b67b237c378fbab388eb571a1867a10430fa5538b6bf6118109d63e1b9c0f220R15
Based on that, I was able to implement the required changes.

**Pull request merged**
