### PR TITLE
Add a script for upgrade testing used by OCP CI

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
Created a script to test upgrade from the latest released version.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by omeryahud** [comment]
/lgtm
Next step would be the OCP CI job?

**Comment by akrejcir** [comment]
> Next step would be the OCP CI job?

Yes the PR is here: https://github.com/openshift/release/pull/15246

**Pull request merged**
