### PR TITLE
Remove unused hack files

### PR DESCRIPTION
**Pull request by vatsalparekh**
**What this PR does / why we need it**:
Initially it was tried to build and run the functional tests inside a container, but it was half baked and was commented out. Doesn't seem like we need it currently.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ksimon1** [comment]
Instead of removing whole work, what has to be done to finish it?

**Comment by vatsalparekh** [comment]
> Instead of removing whole work, what has to be done to finish it?

@ksimon1 I'm not sure if we want to use it anymore
iiric, It would also be difficult to make it work with CI

@akrejcir thoughts?

**Comment by akrejcir** [comment]
CI runs test just by calling `make functests`, so it can build the test any way we want.

I don't think it is necessary to build tests in a container. We use `vendor` to store all our dependencies, and golang compiler versions should be backward compatible, so even if there is a newer version in the test environment, the tests would build correctly.

**Comment by ksimon1** [comment]
ok, thanks for explanation.
/lgtm

**Pull request merged**
