### PR TITLE
Update vendored dependencies

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
Executed:
```
go mod vendor
go mod tidy
```
**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by akrejcir** [comment]
PR does not depend on CI, because it only removes unused files.

/override ci/prow/e2e-functests
/override ci/prow/e2e-upgrade-from-old-operator-functests
/override ci/prow/e2e-upgrade-functests

/cc @omeryahud @kwiesmueller @vatsalparekh

**Comment by kwiesmueller** [comment]
/lgtm
Thanks for doing all those housekeeping PRs!

**Pull request merged**
