### PR TITLE
Nominate kwiesmueller to approvers

### PR DESCRIPTION
**Pull request by vatsalparekh**
**What this PR does / why we need it**:
Nominate kwiesmueller to approvers

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by omeryahud** [comment]
@vatsalparekh Please sign the commit, and remove redundant newline

**Comment by vatsalparekh** [comment]
created #167 instead of this

**Pull request closed without merging**
