### PR TITLE
Improve SSPOperatorReconcilingProperly metric test

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
Wrapped an update in `Eventually()`, so the test is more stable.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by akrejcir** [comment]
Overriding CI. The failing test is flaky and will be fixed once new CDI is released.

/override ci/prow/e2e-upgrade-functests

**Comment by borod108** [comment]
LGTM, great, @ksimon1 can we merge this please, I am using this in a different PR?

**Pull request merged**
