### PR TITLE
chore: rename tekton operands

### PR DESCRIPTION
**Pull request by codingben**
**What this PR does / why we need it**:

Rename Tekton operands from tekton-*.go to
reconcile.go to be similar as in other operands.

**Special notes for your reviewer**:

Not necessarily needed to be backported. As you wish.

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
/approve

I'm fine with it, but please no backport.

**Comment by ksimon1** [comment]
/lgtm
please bare in your mind, that midstream dockerfile will have to be updated after this change.
And I agree with Felix, this PR should not be backported.

**Comment by codingben** [comment]
@ksimon1 Yes, that dockerfile was updated. Thanks!

**Pull request merged**
