### PR TITLE
Adding important log messages

### PR DESCRIPTION
**Pull request by omeryahud**
**What this PR does / why we need it**:
Adding some more log messages to make operator logs more informative

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by akrejcir** [comment]
Some of these messages could probably use debug level. The logging library is confusing. Debug logging is done like: `Logger.V(1).Info(...)`.

We can change it in the future.

**Comment by omeryahud** [comment]
> Some of these messages could probably use debug level. The logging library is confusing. Debug logging is done like: `Logger.V(1).Info(...)`.
> 
> We can change it in the future.

Yea, that's a good point, I will set them as debug

**Comment by kwiesmueller** [comment]
Actually [I started defining operator names as well right now and am conflicting with this](https://github.com/kubevirt/ssp-operator/pull/92/files#diff-f6d56152bde2c23e8384a420483683cbfc8b9d3152bd9c104914c737b8a99cf3R46).
Wasn't sure so far if I should extend the Operand interface, so thanks for that bump.

The names I defined are e.g. `common-templates` which is more coherent with the naming style of our kubernetes resources.
Would you be good with changing the names or prefer me to use something else?
In the HCO PRs they also seem to go with the lower-case format.

**Comment by omeryahud** [comment]
> Actually [I started defining operator names as well right now and am conflicting with this](https://github.com/kubevirt/ssp-operator/pull/92/files#diff-f6d56152bde2c23e8384a420483683cbfc8b9d3152bd9c104914c737b8a99cf3R46).
> Wasn't sure so far if I should extend the Operand interface, so thanks for that bump.
> 
> The names I defined are e.g. `common-templates` which is more coherent with the naming style of our kubernetes resources.
> Would you be good with changing the names or prefer me to use something else?
> In the HCO PRs they also seem to go with the lower-case format.

Hi Kevin, feel free to change them to the lower-case format

**Pull request merged**
