### PR TITLE
data_sources: Always run the operand

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

The operand itself deploys DataImportCrons defined by the SSP CR and DataSources based on the provided common-templates bundle. While the latter functionality should likely reside in the common-templates operand the DataImportCrons functionaility is useful in non-OpenShift environments alongside that of the common-instancetypes operand.

This change now ensures the data_sources operand runs on both OpenShift and non-OpenShift environments.

**Which issue(s) this PR fixes**: 

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
The `data_sources` operand is now always deployed, regardless of the underlying environment being OpenShift or OKD.
```

### CODE REVIEW

**Comment by lyarwood** [comment]
Actually I think I'm going to propose a different approach here with a new operand that isn't dependent on common-templates.

**Comment by 0xFelix** [comment]
Other than that `DataImportCronTemplates` are defined below `CommonTemplates` in the SSP CR I don't see any dependency between the data_sources operand and common-templates. Is there really that much to rework here?

See https://github.com/kubevirt/ssp-operator/blob/master/api/v1beta1/ssp_types.go#L48

/approve

**Comment by lyarwood** [comment]
> Other than that `DataImportCronTemplates` are defined below `CommonTemplates` in the SSP CR I don't see any dependency between the data_sources operand and common-templates. Is there really that much to rework here?
> 
> See https://github.com/kubevirt/ssp-operator/blob/master/api/v1beta1/ssp_types.go#L48
> 
> /approve

Yeah apologies, it isn't obvious from the operand itself but we pass `templatesBundle.DataSources` into `New()` :

https://github.com/kubevirt/ssp-operator/blob/781a27fb7c248a3772812b54bcefab88e65cda90/controllers/setup.go#L60

This is created by the following `template-bundle` code so it's not a direct dependency between the operands but definitely between the template functionality and the `data_sources` operand:

https://github.com/kubevirt/ssp-operator/blob/781a27fb7c248a3772812b54bcefab88e65cda90/internal/template-bundle/bundle.go#L60-L93

I'd really like to understand the reasoning behind this and the creation of the `DataSources` outside of CDI, removing the latter if possible allowing us to break this linkage between the two.

**Comment by 0xFelix** [comment]
/lgtm

Then let's enable the operand for now as is and do the clean up in a separate PR.

**Pull request merged**
