### PR TITLE
Add Resource requests to pods

### PR DESCRIPTION
**Pull request by vatsalparekh**
**What this PR does / why we need it**:
Add resource requests to ssp-operator and template-validator containers

Following the Openshift [CONVENTIONS](https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits), no limits are set, keeping in mind that recourse needs would grow as the cluster grows 

**Which issue(s) this PR fixes**: 

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1953485

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kwiesmueller** [comment]
Thanks!
/lgtm

**Comment by akrejcir** [comment]
/lgtm

Can you fix the link in the PR's description?

**Pull request merged**
