### PR TITLE
Update common-templates to v0.18.1

### PR DESCRIPTION
**Pull request by ksimon1**
Update common-templates bundle to v0.18.1 
**Release note**:
```release-note
Update common-templates bundle to v0.18.1
```

### CODE REVIEW

**Comment by borod108** [comment]
Looks good but we need to see that tests pass after https://github.com/openshift/release/pull/24743 is merged.

**Comment by akrejcir** [comment]
@dominikholler this templates version contains sap hana template. Should it go to version 4.10 or 4.11 ?

**Comment by dominikholler** [comment]
> this templates version contains sap hana template. Should it go to version 4.10 or 4.11 ?
4.10

**Comment by akrejcir** [comment]
The CI will fail, because of a bug in templates parsing.

/hold

**Comment by akrejcir** [comment]
Waiting for: https://github.com/kubevirt/ssp-operator/pull/283

**Pull request closed without merging**
