### PR TITLE
Update common-templates to v0.29.2

### PR DESCRIPTION
**Pull request by ksimon1**
Update common-templates bundle to v0.29.2 
**Release note**:
```release-note
Update common-templates bundle to v0.29.2
```

### CODE REVIEW

**Comment by ksimon1** [comment]
@geetikakay, @kbidarkar  FYI we will be backporting the removal of win2k12 template to 4.16

**Comment by akrejcir** [comment]
Adding renovate is unrelated to this PR. Can you please split it?
We have multiple PRs that update common-templates already, and it is unexpected to find another change in the same PR.

**Comment by ksimon1** [comment]
I am testing renovate on my local fork :) The automation took my main with renovate config, I will remove it.

**Comment by ksimon1** [comment]
@akrejcir fixed

**Comment by jcanocan** [comment]
Thanks @ksimon1!
/lgtm

**Comment by akrejcir** [comment]
Thanks.

/approve

**Pull request merged**
