### PR TITLE
api: Add a config option for vm-console-proxy and deprecate the feature gate

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
These changes are in this PR:
- Deprecated the feature gate for `vm-console-proxy`. It is now ignored.
- Added a new field `.spec.tokenGenerationService` to configure if `vm-console-proxy` should be enabled or not.

**Which issue(s) this PR fixes**: 
Jira: https://issues.redhat.com/browse/CNV-45064

**Release note**:
```release-note
- Added a new field: ".spec.tokenGenerationService" to configure if "vm-console-proxy" should be enabled or not.
- Deprecated the feature gate for `vm-console-proxy`. It is now ignored.
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
/approve

**Comment by codingben** [comment]
> /cc @0xFelix @jcanocan @ksimon1

Hi, why you don't cc me also? If I remember correctly, this was my change to add feature gate of vm-console-proxy [1]. Also Tekton operands.

cc @dominikholler 

[1] https://github.com/kubevirt/ssp-operator/commit/8551c1dbd169cf51105b583d9ed96b5b634d1216

**Comment by akrejcir** [comment]
I only thought that pinging 3 reviewers was enough. It wasn't my intention to not mention you. 
Of course you can review this, all reviews are helpful.

Good idea to mention people that originally wrote the code that I've changed. I will do that in future PRs.

**Comment by jcanocan** [comment]
> > /cc @0xFelix @jcanocan @ksimon1
> 
> Hi @akrejcir, why you don't cc me also? If I remember correctly, this was my change to add feature gate of vm-console-proxy [1]. Also Tekton operands.
> 
> cc @dominikholler
> 
> [1] [8551c1d](https://github.com/kubevirt/ssp-operator/commit/8551c1dbd169cf51105b583d9ed96b5b634d1216)

@codingben Please add the lgtm tag when you are done with your review.

**Comment by codingben** [comment]
> > > /cc @0xFelix @jcanocan @ksimon1
> > 
> > 
> > Hi @akrejcir, why you don't cc me also? If I remember correctly, this was my change to add feature gate of vm-console-proxy [1]. Also Tekton operands.
> > cc @dominikholler
> > [1] [8551c1d](https://github.com/kubevirt/ssp-operator/commit/8551c1dbd169cf51105b583d9ed96b5b634d1216)
> 
> @codingben Please add the lgtm tag when you are done with your review.

Usually in KubeVirt we're waiting to get `/lgtm` and then asking to get `/approve`. From my point of view, it's already reviewed.

**Comment by akrejcir** [comment]
We need both, `/lgtm` and `/approve`, otherwise the bot will not merge the PR.
I think, it is done so multiple people have a chance to look at a PR.

**Pull request merged**
