### PR TITLE
tests: TLS policy: Use insecure TLS for connection to template-validator

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
The current code in functional tests that loads root CA for TLS connection to template-validator does not work when SSP is deployed by OLM.

This commit is a simple fix, where we ignore the validity of the certificate passed by template-validator. This is ok for these tests, because different tests that check behavior of the template-validator would fail if the certificate was invalid.

**Which issue(s) this PR fixes**: 
Fixes: https://issues.redhat.com/browse/CNV-47164

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by jcanocan** [comment]
Thanks!
/lgtm

**Review by 0xFelix — APPROVED** [review]
/approve

**Pull request merged**
