### PR TITLE
[release-v0.11] Add the missing Generate csv

### PR DESCRIPTION
**Pull request by vatsalparekh**
**What this PR does / why we need it**:
This generated change to CSV was missed in #202 

**Which issue(s) this PR fixes**: 

Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=1953485 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ksimon1** [comment]
/lgtm
for some unknown reasons, tests are not running

**Comment by akrejcir** [comment]
Please prefix the PR's description with `[release-v0.11]` to it is obvious this PR is not on master.

The CI is not starting for this branch. Probably my change to the CI configuration was the cause, I will ask for help.

I think this change does not need CI, because CI does not use CSV.

/lgtm
/approve

**Pull request merged**
