### PR TITLE
add eventually command to some tests

### PR DESCRIPTION
**Pull request by ksimon1**
**What this PR does / why we need it**:
add eventually command to some tests.
These tests failed on BM due to bad timing of components creation

**Special notes for your reviewer**:

**Release note**:
```
NONE
```
Signed-off-by: Karel Šimon <ksimon@redhat.com>

### CODE REVIEW

**Comment by ksimon1** [comment]
@akrejcir can you please check this PR?

**Comment by akrejcir** [comment]
I'm surprised that the `Eventually` helps. It should not be needed, because in `BeforeEach` on line 88, there is `waitUntilDeployed()` call, that should wait until SSP operator deploys everything.

Do you know why `waitUntilDeployed()` is not enough?

**Comment by ksimon1** [comment]
there is not problem, that something is not deployed. There is a problem, that sometimes, during update / patch, the api server throws errors e.g. 
```Message: "Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io \"template:view\": the object has been modified; please apply your changes to the latest version and try again",
```

**Comment by akrejcir** [comment]
> ```
> Message: "Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io \"template:view\": the object has been modified; please apply your changes to the latest version and try again",
> ```

That error is usual for update or patch operation, but in this PR, the `Eventually` blocks are around `Get()` methods.
Does the get method return an error too? Maybe some timeout?

**Comment by ksimon1** [comment]
> Does the get method return an error too? Maybe some timeout?
yes, there were problems with timing of tests which `eventually` command solved.

**Comment by akrejcir** [comment]
Ok, Looks good.

/lgtm

**Comment by ksimon1** [comment]
closing in favor of #198

**Pull request closed without merging**
