### PR TITLE
Bump controller-gen and dependencies

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:

This patch updates controller-gen to version `v0.4.0`.
This version generates these versions of manifests:
- `apiextensions.k8s.io/v1`
- `rbac.authorization.k8s.io/v1`

The webhook version is still `v1beta1`, because the server implementation does not support `v1` yet.

Bumped dependencies to:
- `github.com/operator-framework/operator-lib v0.2.0`
- `kubevirt.io/controller-lifecycle-operator-sdk v0.1.1`
- `sigs.k8s.io/controller-runtime v0.6.3`

```release-note
NONE
```

### CODE REVIEW

**Comment by akrejcir** [comment]
/cc @omeryahud @vatsalparekh 

After this PR is merged, you will need to manually remove `controller-gen` and run `make controller-gen` to download the new version. (FYI also for @shwetaap @ksimon1)

**Review by omeryahud — APPROVED** [review]
/lgtm

**Comment by vatsalparekh** [comment]
@akrejcir all tests seem to be failing with `Message: "ssps.ssp.kubevirt.io \"test-ssp\" not found"`
Doesn't seem like a test bug because nothing related to tests has changed here 
/hold

**Comment by akrejcir** [comment]
I think it will be solved by PR #41 .

**Review by omeryahud — APPROVED** [review]
/lgtm

**Comment by akrejcir** [comment]
@vatsalparekh, @ksimon1, @omeryahud, @shwetaap, @jean-edouard, This PR has been merged. Now you will need to manually remove `controller-gen` and run `make controller-gen` to download the new version.

**Pull request merged**
