### PR TITLE
[release-v0.16] Fix total_restored_common_templates metric update

### PR DESCRIPTION
**Pull request by machadovilaca**
**What this PR does / why we need it**:

This is a manual cherry-pick of https://github.com/kubevirt/ssp-operator/pull/559

https://bugzilla.redhat.com/show_bug.cgi?id=2227787

**Which issue(s) this PR fixes**: 

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix total_restored_common_templates metric update
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
What about the changes in `tests/metrics_test.go`?

**Comment by machadovilaca** [comment]
> What about the changes in `tests/metrics_test.go`?

@0xFelix v0.16 still didn't have those e2e tests

**Review by 0xFelix — COMMENTED** [review]
/approve
/retest

**Pull request merged**
