### PR TITLE
Update common-instancetypes to v0.2.0

### LINKED ISSUE #572: Tracker: Sync common-instancetypes `v0.2.0`
/kind enhancement

**What happened**:

https://github.com/kubevirt/common-instancetypes/milestone/4

https://github.com/kubevirt/common-instancetypes/releases/tag/v0.2.0

$subject, should be cut on Wednesday prior to the deadline for SSP on Thursday.

### PR DESCRIPTION
**Pull request by lyarwood**
common-instancetypes: Update bundle to v0.2.0

https://github.com/kubevirt/common-instancetypes/releases/tag/v0.2.0

Fixes #572

**Release note**:
```release-note
Update common-instancetypes bundle to v0.2.0
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm
/approve

**Comment by lyarwood** [comment]
@akrejcir @ksimon1 @0xFelix had to rebase this to resolve the `check_commited_files` issue, if anyone sees this can you `/lgtm` so it can land overnight ahead of the release being cut tomorrow?

**Comment by lyarwood** [comment]
/lgtm


I'm just going to do this as the rebase didn't introduce any changes.

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Pull request merged**
