### PR TITLE
Rename metrics to follow Prometheus naming conventions

### PR DESCRIPTION
**Pull request by machadovilaca**
Signed-off-by: João Vilaça <jvilaca@redhat.com>

**What this PR does / why we need it**:

We are making an effort to uniformize all observability through the KubeVirt components. Right now the `kubevirt_ssp_total_restored_common_templates` does not follow the [naming conventions presented by Prometheus](https://prometheus.io/docs/practices/naming/).

This PR renames `kubevirt_ssp_total_restored_common_templates` metric to `kubevirt_ssp_common_templates_restored_total`

**Release note**:

```release-note
Rename metrics to follow Prometheus naming conventions
```

### CODE REVIEW

**Comment by ksimon1** [comment]
Hi, do you have a specific reason for renaming this metric?

**Comment by machadovilaca** [comment]
Hello @ksimon1,
We are making an effort to uniformize all observability through the KubeVirt components. Right now the `kubevirt_ssp_total_restored_common_templates` does not follow the [naming conventions presented by Prometheus](https://prometheus.io/docs/practices/naming/). Also @sradco has been working on creating an observability best practices document in operator-sdk (operator-framework/operator-sdk#5975) and, as part of the KubeVirt project, we should follow the [best practices we suggest](https://deploy-preview-5975--operator-sdk.netlify.app/docs/best-practices/observability-best-practices/#metrics-naming).

**Comment by ksimon1** [comment]
would you be please so kind and update PR description and commit message, why you do this change?

**Comment by machadovilaca** [comment]
@ksimon1 updated, wdyt?

**Comment by ksimon1** [comment]
/lgtm
Thanks

**Comment by akrejcir** [comment]
Do you want this change in `4.12` release?

**Comment by akrejcir** [comment]
@machadovilaca said that this should go to `4.12`.

**Pull request merged**
