### PR TITLE
Update cnv:vmi_status_running:count

### PR DESCRIPTION
**Pull request by sradco**
**What this PR does / why we need it**:
Update cnv:vmi_status_running:count.
Added the labels instance_type and preference.

**Which issue(s) this PR fixes**: 

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
The cnv:vmi_status_running:count recording rule is now also aggregated by the instance_type and preference labels.
```

### CODE REVIEW

**Comment by sradco** [comment]
@machadovilaca please review

**Comment by sradco** [comment]
Hi @0xFelix  can you please review this PR?

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Comment by akrejcir** [comment]
CI is broken currently. All our PRs are failing.

**Comment by sradco** [comment]
@0xFelix Hi, Am I missing an lgtm?

**Comment by 0xFelix** [comment]
@sradco No, we're still having issues with CI.

**Pull request merged**
