### PR TITLE
Drop replace directive for cpu-nfd-plugin and update some dependencies

### PR DESCRIPTION
**Pull request by omeryahud**
**What this PR does / why we need it**:
Drop replace directive for cpu-nfd-plugin and update some dependencies

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akrejcir** [comment]
It looks like you used `git commit --amend`, and changed the master HEAD by mistake.

**Comment by omeryahud** [comment]
Right, my bad
/hold

**Comment by omeryahud** [comment]
> It looks like you used `git commit --amend`, and changed the master HEAD by mistake.

Fixed

/hold cancel

**Pull request merged**
