### PR TITLE
Remove selected template labels on reconcile

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
The common reconcile method does not remove labels and annotations from resources, which is useful to not remove user-defined labels and annotations.
    
This PR adds a special logic to remove labels and annotations from templates, if they are not user-defined. For example, if the default template for an OS changes, then the label needs to be removed from the old template.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by lyarwood** [comment]
> **What this PR does / why we need it**: The common reconcile method does not remove labels and annotations from resources, which is useful to not remove user-defined labels and annotations.
>
> This PR adds a special logic to remove labels and annotations from templates, if they are not user-defined. For example, if the default template for an OS changes, then the label needs to be removed from the old template.

Should this also be written up as an issue/bug somewhere?

**Comment by lyarwood** [comment]
Regardless of the missing issue/bug this looks fine to me FWIW.

/lgtm

**Comment by akrejcir** [comment]
> 
> Should this also be written up as an issue/bug somewhere?

I think it's not needed. This problem was only in master branch, which was not released.

**Comment by lyarwood** [comment]
> > Should this also be written up as an issue/bug somewhere?
> 
> I think it's not needed. This problem was only in master branch, which was not released.

ACK that's a fair point.

**Pull request merged**
